import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { TimelineItem } from "@/data/case-studies";

interface CaseStudy { eyebrow: string; title: string; summary: string; notice: string; tools: readonly string[]; findings: readonly { label: string; value: string }[]; timeline: readonly TimelineItem[]; outcome: string }

export function CaseStudyPage({ study, next }: { study: CaseStudy; next: { label: string; to: "/case-studies/encrypted-recovery" | "/case-studies/soc-investigation" } }) {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-border/60 bg-background/85 backdrop-blur-xl"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><Button asChild variant="ghost" size="sm"><Link to="/" hash="project"><ArrowLeft />Portfolio</Link></Button><span className="font-display font-bold">Roshan<span className="text-accent">.</span></span></nav></header>
      <main>
        <section className="relative overflow-hidden border-b border-border/60 px-6 pb-20 pt-36"><div className="grid-backdrop pointer-events-none absolute inset-0 opacity-50" /><div className="relative mx-auto max-w-6xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-accent">{study.eyebrow}</p><h1 className="mt-5 max-w-4xl font-display text-4xl font-bold leading-tight sm:text-6xl">{study.title}</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-muted-foreground">{study.summary}</p><div className="mt-8 max-w-3xl border-l-2 border-accent pl-4 text-sm leading-relaxed text-muted-foreground">{study.notice}</div></div></section>
        <section className="mx-auto max-w-6xl px-6 py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{study.findings.map((item) => <div key={item.label} className="rounded-md border border-border bg-card/40 p-5"><p className="font-mono text-xs uppercase tracking-[0.15em] text-primary">{item.label}</p><p className="mt-3 text-sm leading-relaxed text-foreground/90">{item.value}</p></div>)}</div></section>
        <section className="border-y border-border/60 bg-card/20"><div className="mx-auto grid max-w-6xl gap-12 px-6 py-20 lg:grid-cols-[0.65fr_1.35fr]"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-accent">Evidence path</p><h2 className="mt-3 font-display text-3xl font-bold">From signal to finding</h2><p className="mt-4 leading-relaxed text-muted-foreground">A structured timeline keeps observations, actions, and conclusions distinct.</p><div className="mt-7 flex flex-wrap gap-2">{study.tools.map((tool) => <span key={tool} className="chip">{tool}</span>)}</div></div><div className="relative border-l border-primary/40 pl-7">{study.timeline.map((item) => <article key={`${item.time}-${item.title}`} className="relative pb-9 last:pb-0"><span className="absolute -left-[33px] top-1 grid size-3 place-items-center rounded-full bg-accent ring-4 ring-background" /><div className="flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-1.5 font-mono text-xs text-primary"><Clock3 className="size-3" />{item.time}</span><span className="rounded-sm border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{item.kind}</span></div><h3 className="mt-2 font-display text-lg font-semibold">{item.title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{item.detail}</p></article>)}</div></div></section>
        <section className="mx-auto max-w-6xl px-6 py-20"><div className="grid gap-8 border-b border-border pb-20 lg:grid-cols-[0.35fr_1fr]"><div className="flex items-center gap-3 text-accent"><ShieldCheck className="size-7" /><span className="font-mono text-xs uppercase tracking-[0.16em]">Outcome</span></div><p className="font-display text-2xl leading-relaxed text-foreground/90">{study.outcome}</p></div><div className="flex flex-wrap items-center justify-between gap-4 pt-10"><p className="text-sm text-muted-foreground">Continue exploring the investigation portfolio.</p><Button asChild variant="outline"><Link to={next.to}>{next.label}<ArrowRight /></Link></Button></div></section>
      </main>
      <footer className="border-t border-border/60 px-6 py-8 text-center text-sm text-muted-foreground">© 2026 Roshan Muttath Francis · Dublin, Ireland</footer>
    </div>
  );
}
